//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardenShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID { get; set; }
        public string Content { get; set; }
        public Nullable<int> AccManagerID { get; set; }
        public string Answer { get; set; }
        public int AccCustomerID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Approval { get; set; }
    
        public virtual AccCustomer AccCustomer { get; set; }
        public virtual AccManager AccManager { get; set; }
    }
}
